user:
  jay:
    username: 周杰伦
    password: 123456
  william:
    username: william
    password: 123456
  failure:
    username: william
    password: william

url: http://139.159.221.240

mysql:
  db: trading_system
  host: 139.159.221.240
  password: william
  port: 3306
  user: root

redis:
  host: 139.159.221.240
  port: 6379
  db: 0

dingding_group:
  webhook: 这里需要钉钉机器人的webhook

jenkins:
  url: http://139.159.221.240:8080

qywx_group:
  webhook: 这里需要企业微信机器人的webhook

